<?php
/**
 * Created by PhpStorm.
 * User: maxus
 * Date: 05.10.2018
 * Time: 15:07
 */

namespace app\components;


use yii\base\Widget;

class MyWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null) {
            $this->name = 'Guest';
        }
    }

    public function run()
    {
        return "<h1>Hello, {$this->name}!</h1>";
    }

}